### ISSUE TITLE
index not refresh after update from plugin UI

### ISSUE THREAD

**Issue by ZardoZAntony** [chengpohi/elasticshell#15]
![2022-12-13_22-17-28](https://user-images.githubusercontent.com/5212465/207400496-d53532dd-4a92-499f-8449-05669b7743a2.jpg)

need refresh option

**Comment by chengpohi** [comment]
Hi @ZardoZAntony , I could add this feature in next version, but we need to know if we referesh we could not keep the documents in same order when don't query with sort conditions

**Comment by ZardoZAntony** [comment]
@chengpohi thx for prompt reply. Before, I think we need to add "POST/_bulk?refresh" for apply changes to index.  I think we shouldn't keep the sort order after the refresh.

**Comment by chengpohi** [comment]
@ZardoZAntony edql v1.9.10 released, this version supports bulk refresh, commit refresh and manual refresh action. Could you help confirm?


Since Jetbrains still reviewing the new version, you can manually download, and reinstall plugin: [Download from Jetbrains](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/versions/stable/268661)

**Comment by ZardoZAntony** [comment]
Yes, thx! All work fine now!
