### ISSUE TITLE
It has always been loading status(edql version 1.9.9)

### ISSUE THREAD

**Issue by TrillStones** [chengpohi/elasticshell#16]
![1671171043842](https://user-images.githubusercontent.com/32927876/208034463-e325a537-47e4-4143-a385-c3b9749c7fc3.jpg)

elasticsearch version 7.6.2
edql version 1.9.9

cannot load all the infomation from the cluster although i can run POST OR GET request. 
for examples:
GET sms-m-day-send/_mapping

**Comment by chengpohi** [comment]
@TrillStones Thanks your feedback, I will try to reproduce it. and will fix in version 1.9.10

**Comment by chengpohi** [comment]
Hi @TrillStones , edql v1.9.10 released, fixed the es7 incompatible issue, could you try it?

Since Jetbrains still reviewing the new version, you can manually download, and reinstall plugin: [Download from Jetbrains](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/versions/stable/268661)

**Comment by TrillStones** [comment]
> 

It is fixed.Well done! Thanks~
