### ISSUE TITLE
"New File" option

### ISSUE THREAD

**Issue by ljynfo** [chengpohi/elasticshell#18]
When I click on "New File" in IDEA, the options that come up are not in the order I need. Where can I go to set the options and their order for the "New File" option?

![image](https://user-images.githubusercontent.com/42232422/209644332-bd8946dd-14e2-491b-879d-1f1faa66d013.png)

**Comment by chengpohi** [comment]
Hi @ljynfo , There is no easy way to config new edql file order, but I can move the new edql file to the *New* last option in next version.

**Comment by ljynfo** [comment]
@chengpohi 
It would be great if you could help to do it, after all, it affects common operations. Thank you very much indeed. I look forward to your changes helping me solve my troubles

**Comment by chengpohi** [comment]
Hi @ljynfo , edql v1.9.11 released, move the new edql file to last option, could you try it?

![new-edql-option-last](https://user-images.githubusercontent.com/5118048/211014040-2b86eb06-1bd1-485c-9b90-fdedfac7e5a0.png)


Since Jetbrains still reviewing the new version, you can manually download, and reinstall plugin: [Download from Jetbrains](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/versions/stable/274186)


full release document: https://github.com/chengpohi/edql/releases/tag/v1.9.11

**Comment by ljynfo** [comment]
@chengpohi I have seen the problem solved perfectly in the updated plug-in, thank you very much
