### ISSUE TITLE
The timestamp type value returned by the query is incorrect (edql version 1.9.11)

### ISSUE THREAD

**Issue by liucm-it** [chengpohi/elasticshell#19]
![image](https://user-images.githubusercontent.com/37401638/215933165-49c84948-6e7d-496a-b5fe-892f52f86013.png)

elasticsearch version 5.5.1
edql version 1.9.11

The timestamp return value is incorrect

Actual value: 1675153475000
Query return value: 2147483647

**Comment by chengpohi** [comment]
Hi @liucm-it , it's a bug(caused by in 1.9.2 version integer overflow), I have found in Spring Festival also, I will fix and release in this week. Thanks your feedback 👍👍👍

**Comment by chengpohi** [comment]
Hi @liucm-it  edql v1.9.12 released, fix the number overflow issue.

Since Jetbrains still reviewing the new version, you can manually download, and reinstall plugin: [Download from Jetbrains](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/versions/stable/285778)

full release document: https://github.com/chengpohi/edql/releases/tag/v1.9.12

**Comment by liucm-it** [comment]
@chengpohi Ok, thank you for your hard work
