### ISSUE TITLE
Index starting with a number causes "<identifier 0> expected, got 'x'" error

### ISSUE THREAD

**Issue by motofix** [chengpohi/elasticshell#22]
If the index names is starting with a number, like `0_my_index`, the following error prevents request execution:
`<identifier 0> expected, got '0'`

**Comment by chengpohi** [comment]
Got it, I will fix the parser issue in next version, will release in this week.

**Comment by chengpohi** [comment]
Hi @motofix , this issue is fixed in version [v1.9.19](https://github.com/chengpohi/edql/releases/tag/v1.9.19)
this issue is caused the parser failed to handle number with char, it's fixed.

Since Jetbrains still reviewing the new version, you can manually download, and reinstall plugin: [v1.9.19](https://github.com/chengpohi/edql/releases/tag/v1.9.19)

**Comment by motofix** [comment]
Thanks !
