### ISSUE TITLE
Can't connect to urls which don't end in a port

### ISSUE THREAD

**Issue by obp3ter** [chengpohi/elasticshell#23]
When trying to connect to a URL similar to: _https://ourserver.company.com/stage1-kibana_ the test connection returns _Connect failed: 404 page not found_.
I noticed, that in the list of connections it appears with _:-1_ appended.

**Comment by chengpohi** [comment]
Hi @obp3ter , got it, I will try to reproduce this issue. 

and if you specify port on URL, Would it connect successfully?  example: https://ourserver.company.com:443/stage1-kibana

**Comment by obp3ter** [comment]
Unfortunately it doesn't.

**Comment by chengpohi** [comment]
@obp3ter ok, I will try tro reproduce this issue.

**Comment by chengpohi** [comment]
Hi @obp3ter this issue is reproduced when use elasticsearch url with redirected url:

https://stackoverflow.com/questions/61138183/elesticsearch-rest-http-request-through-redirected-url

and I will fix it in version 1.9.20 in this weekeend

**Comment by chengpohi** [comment]
Hi @obp3ter  , this redirected url issue is fixed in version [v1.9.20](https://github.com/chengpohi/edql/releases/tag/v1.9.20), if there is still has any issue pls let me know. thanks your feedback.

Since Jetbrains still reviewing the new version, you can manually download, and reinstall plugin: [v1.9.20](https://github.com/chengpohi/edql/releases/tag/v1.9.20)

**Comment by obp3ter** [comment]
Hi @chengpohi, I tested it. This issue is solved, now I have a new one I'll make a separate issue.
