### ISSUE TITLE
cannot use HTTP proxy

### ISSUE THREAD

**Issue by 913072870** [chengpohi/elasticshell#28]
How to use an HTTP proxy to connect to ES

**Comment by chengpohi** [comment]
Hi @913072870 , for now *EDQL* doesn't support http proxy, I will try to  add this feature to support http proxy, maybe we can release in next version : 1.9.27, thanks your feedback. 👍

**Comment by chengpohi** [comment]
Hi @913072870  , this feature is supported in version [v1.9.27](https://github.com/chengpohi/edql/releases/tag/v1.9.27), so now you connect your Elasticsearch by using your Intellij system http proxy. if you meet any issue, please let me know.

![image](https://github.com/chengpohi/edql/assets/5118048/c3768734-21b7-4c46-81d5-0a498778a1e8)


Since Jetbrains still reviewing the new version, you can manually download, and reinstall plugin: [v1.9.27](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/versions/stable/354033)

**Comment by 913072870** [comment]
👍

**Comment by chengpohi** [comment]
Hi @913072870 please use the latest version: [v1.9.27](https://github.com/chengpohi/edql/releases/tag/v1.9.27), and also you can download from Jetbrains market [v1.9.27](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/versions/stable/354509)

Thanks your feedback 🥰🥰🥰, If you meet any issue please let me know.


![image](https://github.com/chengpohi/edql/assets/5118048/7fbedd1d-93fa-4481-9712-8982489da132)
