### ISSUE TITLE
Issue with multiple connections

### ISSUE THREAD

**Issue by tudorpie** [chengpohi/elasticshell#31]
I have multiple connections as such:

PROD
QA
LOCAL

The local and qa one use `localhost:9291` for host  and a user/pass combo.
What QA does different is that it has ssh connection with key pair. (To an external server)

HOWEVER: The QA connection seems to actually be a similar LOCAL connection

NOTE:
PROD server is similar to QA (different key/pair and SSH Host though) BUT it has a different host: app-etc.ninja:9291

**Comment by chengpohi** [comment]
Hi @tudorpie , so what's the problem you meet?  Could not connect **prod** and **qa** host by ssh tunnel?

**Comment by tudorpie** [comment]
I could connect to prod; qa connection actually connected to localhost instead of going to remote server.

**Comment by chengpohi** [comment]
@tudorpie got it I will try to reproduce it with ssh key pair

**Comment by chengpohi** [comment]
Hi @tudorpie  please try the latest version: [v1.9.31](https://github.com/chengpohi/edql/releases), and also you can download from Jetbrains market [v1.9.31](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/versions/stable/397166).

This issue is caused by refactor in v1.9.28: jsch tunnel connect not correctly handle by connection.

Thanks your feedback, If you meet any issue please let me know.


![image](https://github.com/chengpohi/edql/assets/5118048/6854d981-7593-4f4e-932c-56707bc5c45c)
