### ISSUE TITLE
SSH Tunnel with password protected key

### ISSUE THREAD

**Issue by JeroenTriptic** [chengpohi/elasticshell#43]
In our workflow the Elastic instance is on a remote server that is protected with a password protected SSH key. In the PhpStorm SSH Configurations I have already added this server and can connect to it. I will be prompted for the password of the SSH key the first time I connect and it remembers it until I close PhpStorm.
I would like to also be able to use this connection as SSH Tunnel for this plugin if possible, but at least I would like to be able to setup any connection with a password protected SSH key.

**To Reproduce**
1. Go to Connections
2. Check "Connect with SSH Tunnel"
3. Select "Key pair" as "Authorization Type"
4. Select a password protected key as "Private key file"
5. Click "Test Connection"

**Expected behavior**
A prompt to enter the Keys password. And a successful connection.

**Comment by chengpohi** [comment]
Hi @JeroenTriptic , since idea ssh connection only available for ultimate version, community version is not available.  so we only can use our custom ssh connection, the **Key pair** with password you can input password by **Passphrase** field, this is hidden by dialog, you need to maxmize dialog, I will update UI in next version):

<img width="621" alt="image" src="https://github.com/chengpohi/edql/assets/5118048/08e2fe81-8063-472e-bfe4-7434106d2f62">

If you have any other issue, pls let me know.

**Comment by JeroenTriptic** [comment]
Thank you for the reply. I didn't know that the SSH configuration wasn't available for everyone and indeed after resizing the window I did see the Passphrase field and it is working now!
