### ISSUE TITLE
the lost of big number

### ISSUE THREAD

**Issue by dy033** [chengpohi/elasticshell#45]
![image](https://github.com/user-attachments/assets/edeca8ba-bdc4-447a-8ff7-8671289f45fa)

the type of "_id" is string, and it is equal "item_id"
the type of "item_id" is long

the last two number of "item_id" is loss and display zero

the problem as well as happen when query use item_id  

use kibana do not has this problem

the number is  7405486664228818988

**Comment by chengpohi** [comment]
Hi @dy033 , this issue is fixed by 1.0.14, you can download from Jetbrains market [v1.10.14](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/edit/versions/stable/604801) or manual install by [Github release v1.10.14](https://github.com/chengpohi/edql/releases).

Thanks your feedback and contribution 👍👍👍
