### ISSUE TITLE
Passwords aren't saved according to the System Settings > Passwords configuration

### ISSUE THREAD

**Issue by JeroenTriptic** [chengpohi/elasticshell#47]
**Describe the bug**
The passwords are saved in the config of the plugin instead of in the keystore as configured in System Settings > Passwords.

**To Reproduce**
1. Add a connection that uses an SSH tunnel
2. Export the settings
3. The password can be found in plain text

**Expected behavior**
I would expect a password to be saved in the keystore instead of in the config files.

**Comment by chengpohi** [comment]
@JeroenTriptic got it, I will change it in next version 1.10.5, Thansk your feedback

https://www.jetbrains.com/help/idea/reference-ide-settings-password-safe.html

**Comment by chengpohi** [comment]
Hi @JeroenTriptic, 

this is fixed by 1.0.15,  after install this version, it will automatically migrate passwords to keychain(macos) by PasswordSafe.

You can download from Jetbrains market [v1.10.15](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/edit/versions/stable/624919) or manual install by [Github release v1.10.15](https://github.com/chengpohi/edql/releases/tag/v1.10.15), if there is any issue please let me know

Thanks your feedback
