### ISSUE TITLE
feature request: make properties filter searchable 

### ISSUE THREAD

**Issue by BMomani** [chengpohi/elasticshell#49]
filter button is crucial to make you focus on what properties you are interested in especially when you have a big document 
but it lack the quick search making it not useful when you give up searching for the property you want to see only

![image](https://github.com/user-attachments/assets/328d2f4b-9509-4536-b14c-9d0d2d0c51ef)

the ask is to make filter UI filterable (a quick search for a specific property)

thanks for the great work

**Comment by chengpohi** [comment]
Hi @BMomani  , this feature is fixed by 1.0.18, you can download from Jetbrains market [v1.10.18](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/edit/versions/stable/647011) or manual install by [Github release v1.10.18](https://github.com/chengpohi/edql/releases/tag/v1.10.18).

<img width="255" alt="image" src="https://github.com/user-attachments/assets/673c1f66-6138-4a3a-b0d6-5fc3085355f2">


Thanks your feedback 👍👍👍
